const productData = [
  {
    productId: '1',
    productImg: '/img/products/1.jpg',
    productName: 'Little Armchair Sheepskin',
    productPrice: '958$',
    itemCategory: 'CHAIRS',
  },
  {
    productId: '2',
    productImg: '/img/products/2.jpg',
    productName: 'Pop-Up Toaster',
    productPrice: '50$',
    itemCategory: 'KITCHEN',
  },
  {
    productId: '3',
    productImg: '/img/products/3.png',
    productName: 'Lamp Light Blue',
    productPrice: '25$',
    itemCategory: 'LAMPS',
  },
  {
    productId: '4',
    productImg: '/img/products/4.jpg',
    productName: 'Pulp Unit - 5 Compartments',
    productPrice: '209$',
    itemCategory: 'FURNITURES',
  },
  {
    productId: '5',
    productImg: '/img/products/5.jpg',
    productName: 'Golden Modern Light',
    productPrice: '175$',
  },
  {
    productId: '6',
    productImg: '/img/products/6.jpg',
    productName: 'Body Oil 200ml',
    productPrice: '32$',
    itemCategory: 'SKINCARE',
  },
  {
    productId: '7',
    productImg: '/img/products/7.jpg',
    productName: 'Black and White Lamp',
    productPrice: '200$',
    itemCategory: 'LAMPS',
  },
  {
    productId: '8',
    productImg: '/img/products/8.jpg',
    productName: 'Gejst Shelf A Black Ash/Black',
    productPrice: '149$',
    itemCategory: 'FURNITURES',
  },
  {
    productId: '9',
    productImg: '/img/products/9.png',
    productName: 'Cube Lolo Vase Black',
    productPrice: '85$',
    itemCategory: 'FURNITURES',
  },
  {
    productId: '10',
    productImg: '/img/products/10.jpg',
    productName: 'Traditional Armchair',
    productPrice: '120$',
    itemCategory: 'CHAIRS',
  },
  {
    productId: '11',
    productImg: '/img/products/11.jpg',
    productName: 'The Sun Pendant Black',
    productPrice: '149$',
    itemCategory: 'LAMP',
  },

  {
    productId: '12',
    productImg: '/img/products/12.png',
    productName: 'Simple Golden Lamp',
    productPrice: '49$',
    itemCategory: 'LAMPS',
  },
  {
    productId: '13',
    productImg: '/img/products/13.jpg',
    productName: 'Unbleached Cotton Pads 180',
    productPrice: '99$',
    itemCategory: 'SKINCARE',
  },
  {
    productId: '14',
    productImg: '/img/products/14.png',
    productName: 'Oak Spanish Chair',
    productPrice: '50$',
    itemCategory: 'CHAIRS',
  },
  {
    productId: '15',
    productImg: '/img/products/15.jpg',
    productName: 'Copenhagen Armchair',
    productPrice: '542$',
    itemCategory: 'CHAIRS',
  },
  {
    productId: '16',
    productImg: '/img/products/16.jpg',
    productName: 'Anti Dark Light',
    productPrice: '123$',
    itemCategory: 'ELECTRONICS',
  },
  {
    productId: '17',
    productImg: '/img/products/17.png',
    productName: 'Table Lamp',
    productPrice: '47$',
    itemCategory: 'LAMPS',
  },
  {
    productId: '18',
    productImg: '/img/products/18.png',
    productName: 'Mat Black Lamp',
    productPrice: '78$',
    itemCategory: 'LAMPS',
  },

  {
    productId: '19',
    productImg: '/img/products/19.jpg',
    productName: 'Comfy Chair',
    productPrice: '256$',
    itemCategory: 'CHAIRS',
  },
  {
    productId: '20',
    productImg: '/img/products/20.jpg',
    productName: 'Body Oil 50ml',
    productPrice: '52$',
    itemCategory: 'SKINCARE',
  },
];
export default productData;
